#!/usr/bin/env node

'use strict';

const path = require('path');

// in v2, instead of FastBootAppServer as your means to customize, we provide FastBootServer
// TODO: change name: FastBootV2AppServer?
const FastBootServer = require('ember-alt-fastboot-app-server/src/backing-classes/cluster-master');
const serialize = require('ember-alt-fastboot-app-server/src/utils/serialization').serialize;

const config = {
  distPath: path.join(__dirname, '../'),
  workerPath: path.join(__dirname, './cluster-worker.js'),
  host: '0.0.0.0',
  port: '4200',
  workerCount: 1,
  minifyHtml: true,
  buildSandboxGlobals(globalOptions) {
    return Object.assign({}, globalOptions, {
      process
    });
  }
};

const master = new FastBootServer(config);

master.start();
